sudo: required

language: python

services:
  - docker

jobs:
  include:
    - stage: build, test and push docker image
      script:
      - docker build -t docker-mycroft .
      - docker images
      - docker tag docker-mycroft $DOCKER_USERNAME/docker-mycroft
      - docker run -d -p 127.0.0.1:8181:8181 --name mycroft-docker $DOCKER_USERNAME/docker-mycroft
      - docker ps | grep -q "mycroft-docker"
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $DOCKER_USERNAME/docker-mycroft
