sudo: required

dist: xenial

language: python
python:
  - "3.6"

services:
  - docker  
  
before_install:
  - sudo apt-get update
  - chmod u+x host_setup.sh && sudo ./host_setup.sh

jobs:
  include:
    - stage: build, test and push docker image
      script:
      - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - docker build -t docker-mycroft .
      - docker images
      - docker tag docker-mycroft $DOCKER_USERNAME/docker-mycroft-rpi
      - docker run -d -p 127.0.0.1:8181:8181 --name mycroft-docker $DOCKER_USERNAME/docker-mycroft-rpi
      - docker ps | grep -q "mycroft-docker"
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $DOCKER_USERNAME/docker-mycroft-rpi
